name: Trigger auto deployment for dzfpyapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/dzfpyapp-AutoDeployTrigger-7f9a3b58-d74c-4603-b4a4-28ca2f589798.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DZFPYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DZFPYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DZFPYAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.DZFPYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DZFPYAPP_REGISTRY_PASSWORD }}
          containerAppName: dzfpyapp
          resourceGroup: dzf-capp-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


